### ISSUE TITLE
Strange, unexplainable 404 on homepage

### ISSUE THREAD

**Issue by ZachOhara** [danielgrimshaw/danielgrimshaw.github.io#1]
Your homepage here 404's. I dont' know why. Probably you don't either. I reccommend just deleting the repo and starting over.

@danielgrimshaw @danielgrimshaw @danielgrimshaw @danielgrimshaw @pranavmathur

**Comment by danielgrimshaw** [comment]
If you looked at the code, you would see that there is currently no index.php or index.html or index page in general. I just added this repo to play with php, js, html, xml, and web based java/python.

**Comment by danielgrimshaw** [comment]
Just as a note, the website is now up, but github does not like php, ruby, python, or perl (this is why thunderbots-5604 does not have a .github.io website. The full website is [here](http://udkk43f8b53d.danielgrimshaw.koding.io/index.html).

http://udkk43f8b53d.danielgrimshaw.koding.io/index.html

**Comment by danielgrimshaw** [comment]
@ZachOhara
